server:
  port: 8080
app:
  jwtSecret: Aslkdjalwidjaslmdnmcnvxleflisdjflskejflidsjflskjefasdsadsadasdqweqewqe123asdsadzxczcadw
  googleClientId: 615612093999-3ommfatdj5qm627gs6um9dneft4civdv.apps.googleusercontent.com
spring:
  application:
    name: nguyen-duy-dev
    frontend-url: http://localhost:3000
  profiles:
    active: dev
  data:
    redis:
      host: localhost
      port: 6379

